# Generated by Django 5.2.6 on 2025-09-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('device_registered', 'Device Registered'), ('device_online', 'Device Online'), ('device_offline', 'Device Offline'), ('heartbeat', 'Heartbeat'), ('lock_auto', 'Auto Lock'), ('lock_manual', 'Manual Lock'), ('lock_forced', 'Forced Lock'), ('unlock_attempt', 'Unlock Attempt'), ('unlock_success', 'Unlock Success'), ('unlock_failed', 'Unlock Failed'), ('unlock_blocked', 'Unlock Blocked'), ('action_lock_sent', 'Lock Command Sent'), ('action_unlock_sent', 'Unlock Command Sent'), ('action_restart_sent', 'Restart Command Sent'), ('action_screenshot_sent', 'Screenshot Command Sent'), ('action_completed', 'Action Completed'), ('action_failed', 'Action Failed'), ('action_timeout', 'Action Timeout'), ('multiple_failed_attempts', 'Multiple Failed Attempts'), ('security_violation', 'Security Violation'), ('suspicious_activity', 'Suspicious Activity'), ('policy_updated', 'Policy Updated'), ('agent_updated', 'Agent Updated'), ('config_changed', 'Configuration Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('admin_action', 'Admin Action')], help_text='Type of event', max_length=50),
        ),
    ]
